spring:
  application:
    name: shopping-app-service
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SELECT 1
      connection-timeout: 36000000
      idle-timeout: 0
      poolName: shopping-app-pool
      maximum-pool-size: 20
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    locations:
      - classpath:/db/migrations
    table: webservice_schema_version
    baseline-version: 0
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 822175996451-p5d1of26olctf2lunj6kkpjv5qlc23pe.apps.googleusercontent.com
            clientSecret: Qf2Rw2WCNdYyY5V6te_vUl63
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

server:
  servlet:
    context-path: /api/service

jwt:
  passwordStrength: 0
  secret: SECRET_IS_HERE
  issuer: altrooist-api
  authorizedRedirectUris:
    - http://localhost:4200/oauth2/redirect
