create table if not exists user_details (
       id int8 generated by default as identity,
        created_by varchar(255) not null,
        created_on timestamp not null,
        updated_by varchar(255),
        updated_on timestamp,
        email varchar(255) not null,
        image_url varchar(255),
        name varchar(255) not null,
        password varchar(255),
        provider varchar(255),
        provider_id varchar(255),
        user_type varchar(255) not null,
        primary key (id)
 );


alter table if exists user_details
       drop constraint if exists user_email_constraint;

alter table if exists user_details
       add constraint user_email_constraint unique (email);